version: "3.8"
services:
  config-server:
    image: config-server:latest
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    ports:
        - "9010:9010"

    environment: 
        # Important for clients to register with eureka
        - eureka.client.serviceUrl.defaultZone=http://service-registry:8761/eureka/
        
    depends_on:
        - service-registry
    links:
        - service-registry

        
    
