version: "3.8"
services:
  cloud-gateway:
    image: cloud-gateway:latest
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    ports:
        - "9191:9191/tcp"

        
    
